version: '2'

services:
  wordpress:
    build: 
      context: ./wordpress
      args:
        HASH: 5f52157d461af74dc8b2f2b3492d6806e8853a57
        WORDPRESS_DB_PASSWORD: example
    restart: always
    ports: 
      - 5001:80

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
