version: '3'

services:
  wordpress:
    image: "roo/wordpress:$NAME"
    build: 
      context: ./wordpress
      args:
        HASH: "$HASH"
        WORDPRESS_DB_PASSWORD: example
    networks:
      - "$NAME"
    restart: always
    ports: 
      - "$PORT:80"

  mysql:
    image: mysql:5.7
    restart: always
    networks:
      - "$NAME"
    environment:
      MYSQL_ROOT_PASSWORD: example

networks:
  "$NAME":
